FROM python:3.11-slim-bullseye
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY env/requirements.txt /app/env/

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r /app/env/requirements.txt

CMD ["/bin/bash"]